PACKAGE_NAME=usbip-backports
PACKAGE_VERSION=6.11-1

MAKE[0]="'make' \"KDIR=$kernel_source_dir\""

BUILT_MODULE_NAME[0]=usbip-core
DEST_MODULE_LOCATION[0]="/kernel/drivers/usb/usbip/"

BUILT_MODULE_NAME[1]=usbip-host
DEST_MODULE_LOCATION[1]="/kernel/drivers/usb/usbip/"

BUILT_MODULE_NAME[2]=usbip-vudc
DEST_MODULE_LOCATION[2]="/kernel/drivers/usb/usbip/"

BUILT_MODULE_NAME[3]=vhci-hcd
DEST_MODULE_LOCATION[3]="/kernel/drivers/usb/usbip/"

PATCH[0]="0001-iov_iter-direction-initializer-new-names.patch"
PATCH[1]="0002-Include-linux-version.h.patch"
PATCH[2]="0003-Conditionally-use-sk_use_task_frag.patch"
PATCH[3]="0004-Add-USBIP_URB_-URB-transfer-flags.patch"
PATCH[4]="0005-vhci_hcd-Conditionally-use-remove_new-callback.patch"
PATCH[5]="0006-Conditionally-define-kthread_stop_put.patch"
PATCH[6]="0007-vudc-Conditionally-use-remove_new-callback.patch"
PATCH[7]="0008-Conditionally-use-old-driver-member-name.patch"
