name: on-push

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install build-essential linux-headers-generic
    - name: Build
      run: |
        set -- /usr/src/linux-headers-*-generic
        make -C "$1" M="$PWD" modules
